### ISSUE TITLE
Use seconds since epoch (unix time) for blog post time

### ISSUE THREAD

**Issue by Accurate0** [Techypanda/Techytechster#11]
https://github.com/Techypanda/Techytechster/blob/AdminSite/api/blog/create.go#L146-L148

**Comment by Techypanda** [comment]
OOPSIE WOOPSIE!!
UwU We made a fucky wucky!! a wittle fucko boingo! The code monkeys at our headquarters are workign VEWY HAWD to fix this!
:(

**Comment by Techypanda** [comment]
da issue has now be wesowved mw singh, pwease wemain cawm and happy it ish now unix time uwu,
u can see it impwemented on https://api.techytechster.com/blog/all ow on da admin static site thankies fow youw contwibution
