### ISSUE TITLE
fix ci/cd

### ISSUE THREAD

**Issue by ghost** [Techypanda/Techytechster#13]

**Comment by Techypanda** [comment]
![8406cc458a3e91669152c5c6aa22aad9](https://user-images.githubusercontent.com/37826825/124290403-f9063900-db85-11eb-861b-edb581985236.png)
thanks man...

**Comment by Techypanda** [comment]
yeah it looks like this was caused from a github error? (seems to be fine now will reopen issue if it occurs again)
